version: "2"

services:
  postgres:
    container_name: pocketband-db
    build:
      context: ./postgres_db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_volume:

